# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TikiTaka' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod ‘RxSwift’, ‘~> 5’
pod ‘RxCocoa’, ‘~> 5’
pod ‘Alamofire’, ‘~> 5.2’
pod 'Kingfisher', '~> 5.0'
pod 'Socket.IO-Client-Swift', '~> 15.2.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'RxDataSources', '~> 4.0'
pod 'Moya', '~> 14.0'
pod 'Moya/RxSwift', '~> 14.0'

  # Pods for TikiTaka

end
